name: Laravel Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Container Up
        run: docker compose -p laravel_github -f docker-compose-github.yml up -d
      - name: Install composer dependencies
        run: composer install
      - name: Copy .env.example to .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
