name: Laravel Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Container up
        run: docker compose -p laravel_github -f docker-compose-github.yml up -d
      - name: Copy .env.example to .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Chmod
        run: sudo chmod 777 -R storage
      - name: Install composer dependencies
        run: docker exec laravel_github composer install
      - name: Artisan commands
        run: |
          docker exec laravel_github apt update
          docker exec laravel_github apt install nano
          docker exec laravel_github php artisan key:generate
          docker exec laravel_github php artisan migrate
          docker exec laravel_github php artisan cache:clear
          docker exec laravel_github php artisan config:cache
          docker exec laravel_github php artisan route:cache
