name: Laravel Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env.example to .env
        run: docker compose -p laravel_github -f docker-compose-github.yml up -d
