name: Laravel Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Container up
        run: docker compose -p laravel_github -f docker-compose-github.yml up -d
      - name: Install composer dependencies
        run: docker exec laravel_github composer install
      - name: artisan
        run: |
          docker exec laravel_github php artisan migrate
          docker exec laravel_github php artisan cache:clear
          docker exec laravel_github php artisan config:cache
          docker exec laravel_github php artisan route:cache
